# Generated by Django 5.1.7 on 2025-03-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.TextField(unique=True)),
                ('ward_no', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bed',
            name='bed_id',
        ),
        migrations.CreateModel(
            name='PatientsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('description', models.TextField()),
                ('bed_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_number', to='user_management.bed')),
                ('doctor', models.ManyToManyField(blank=True, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_name', to=settings.AUTH_USER_MODEL)),
                ('ward_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_number', to='user_management.ward')),
            ],
        ),
        migrations.DeleteModel(
            name='Patients_information',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
