# Generated by Django 5.1.7 on 2025-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_ward_remove_bed_bed_id_patientsinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_no',
            field=models.TextField(unique=True),
        ),
    ]
