# Generated by Django 5.1.7 on 2025-03-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_bed_bed_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='ward_no',
        ),
    ]
