# Generated by Django 5.1.7 on 2025-03-27 09:22

import django.db.models.deletion
import user_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_ward_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to=user_management.models.report_upload_path)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_id', to='user_management.patientsinformation')),
            ],
        ),
    ]
