# Generated by Django 5.1.7 on 2025-03-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_report_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bool_presure', models.TextField(max_length=3)),
                ('sugar', models.TextField(max_length=3)),
                ('oxygen', models.TextField(max_length=3)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_id', to='user_management.patientsinformation')),
            ],
        ),
    ]
