# Generated by Django 5.1.7 on 2025-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_patienthealthreport_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreport',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patienthealthreport',
            name='bool_presure',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patienthealthreport',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patienthealthreport',
            name='oxygen',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patienthealthreport',
            name='sugar',
            field=models.CharField(max_length=3),
        ),
    ]
