# Generated by Django 5.1.7 on 2025-03-31 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_patienthealthreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinformation',
            name='patient_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
