# Generated by Django 5.1.7 on 2025-03-31 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_patientsinformation_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
