# Generated by Django 5.1.7 on 2025-03-31 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_report_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthreport',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_report_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
