# Generated by Django 5.1.7 on 2025-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_patienthealthreport_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreport',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
