# Generated by Django 5.1.7 on 2025-03-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_patienthealthreport_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthealthreport',
            old_name='bool_presure',
            new_name='bood_presure',
        ),
    ]
