# Generated by Django 5.1.7 on 2025-04-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_rename_bool_presure_patienthealthreport_bood_presure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('visit', models.BooleanField(default=False)),
                ('doctor_visit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visit_id', to=settings.AUTH_USER_MODEL)),
                ('visitred_patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_patient_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
