# Generated by Django 5.1.7 on 2025-04-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_doctorvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorvisit',
            old_name='visitred_patient_id',
            new_name='visited_patient_id',
        ),
    ]
