# Generated by Django 5.1.7 on 2025-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_rename_visitred_patient_id_doctorvisit_visited_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvisit',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
