# Generated by Django 5.1.7 on 2025-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_doctorvisit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charges',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
