# Generated by Django 5.1.7 on 2025-04-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_user_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charges',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
