# Generated by Django 5.1.7 on 2025-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_alter_user_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinformation',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientsinformation',
            name='discharge_date',
            field=models.DateField(auto_now=True),
        ),
    ]
