# Generated by Django 5.1.7 on 2025-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_patientsinformation_discharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsinformation',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='patientsinformation',
            name='discharge_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='charges',
            field=models.IntegerField(default=0),
        ),
    ]
