# Generated by Django 5.1.7 on 2025-04-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_remove_patientsinformation_discharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_charges',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
