# Generated by Django 5.1.7 on 2025-04-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_ward_ward_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinformation',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientsinformation',
            name='discharge_date',
            field=models.DateField(auto_now=True),
        ),
    ]
