# Generated by Django 5.1.7 on 2025-04-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_patientsinformation_discharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsinformation',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='patientsinformation',
            name='discharge_date',
        ),
    ]
