# Generated by Django 5.1.7 on 2025-04-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_patientsinformation_discharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsinformation',
            name='download',
            field=models.BooleanField(default=False),
        ),
    ]
