# Generated by Django 5.1.7 on 2025-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_patientsinformation_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
