# Generated by Django 6.0.4 on 2026-04-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_alter_user_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthealthreport',
            old_name='bood_presure',
            new_name='blood_pressure',
        ),
    ]
